backend:
  name: github
  repo: achapman77/gatsby-starter-template-plus
  branch: main

site_url: https://gatsby-netlify-cms-starter-template-plus.netlify.app/
display_url: https://gatsby-netlify-cms-starter-template-plus.netlify.app/
logo_url: src/assets/gatsby-atronaut.png

media_folder: content/images/uploads
public_folder: ../images/uploads

collections:
  - name: blogs
    label: Blogs
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "SEO Title", name: "title", widget: "string", pattern: ['.{20,}', "Must have at least 20-65 characters"]}
      - {label: "SEO Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 
      - {label: "Image", name: "image", widget: "image", required: false} 
      
  - name: "site_content"
    label: "Site Content"
    files:
      # - label: "Site Logos"
      #   name: site_logos
      #   file: content/site-data/site-logos.md
      #   fields:
      #     - label: "Logos"
      #       name: "logos"
      #       widget: object
      #       fields:
      #         - {label: "Alt Text", name: "alt", widget: "string", required: false}
      #         - {label: "Upload Dark on Light Logo", name: "logo_dark", widget: "image", required: false}
      #         - {label: "Upload Light on Dark Logo", name: "logo_light", widget: "image", required: false}
      #         - {label: "Upload Icon", name: "icon", widget: "image", required: false}
      #         - {label: "Upload Favicon", name: "favicon", widget: "image", required: false}
      - label: "Contact Info"
        name: contact_info
        file: content/site-data/contact_info.md
        fields:
          - {label: "Business Name", name: "business_name", widget: "string", required: false}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Fax", name: "fax", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - label: "Business Address" 
            name: "business_address"
            widget: "object" 
            fields:
              - {label: "Street", name: "street", widget: "string", required: false}
              - {label: "Street2", name: "street2", widget: "string", required: false}
              - {label: "City ", name: "city", widget: "string", required: false}
              - {label: "State", name: "state", widget: "string", required: false}
              - {label: "Zipcode", name: "zipcode", widget: "string", required: false}
              - {label: "Google Map Link", name: "map_link", widget: "string", required: false}
          - label: "Contact Section Content" 
            name: "contact_section_content"
            widget: "object" 
            fields:
              - {label: "Header", name: "header", widget: "string", required: false}
              - {label: "Sub Header", name: "sub_header", widget: "string", required: false}
              - {label: "Header Image", name: "header_image", widget: "image", required: false}
              - {label: "Contact Info Title ", name: "contact_info_title", widget: "string", required: false}
              - {label: "Form Title", name: "form_title", widget: "string", required: false}
      - label: "Social Media"
        name: social_media
        file: content/site-data/social_media.md
        fields:
          - label: Social Media
            name: social_media
            widget: list
            fields: 
              - {label: "Select Social Media", name: "select_social_media", widget: "select", options: ["LinkedIn", "Facebook", "Instagram", "Twitter"]}
              - {label: "Profile Link", name: "profile_link", widget: "string"}
      - label: "FAQ"
        name: "faq"
        file: content/site-data/faq.md
        fields:
          - label: FAQ
            name: faq
            widget: list
            fields: 
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "text"}
              - {label: "Link to Video Answer", name: "video_link", widget: "string"}
      - label: "Media Articles"
        name: "media_articles"
        file: content/site-data/media_articles.md
        fields:
          - label: Media Articles
            name: media_articles
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Publish Date", name: "publish_date", widget: "string"}
              - {label: "Author", name: "author", widget: "string"}
              - {label: "Publisher", name: "publisher", widget: "string"}
              - {label: "Publisher Logo", name: "publisher_logo", widget: "image"}
              - {label: "Article Excerpt", name: "article_excerpt", widget: "text"}
              - {label: "Article Link", name: "article_link", widget: "text"}
      - label: "Testimonials"
        name: "testimonials"
        file: content/site-data/testimonials.md
        fields:
          - label: Testimonials
            name: testimonials
            widget: list
            fields: 
              - {label: "Testimonial", name: "testimonial", widget: "text"}
      - label: "Team Members"
        name: "team_members"
        file: content/site-data/team.md
        fields:
          - label: Team Members
            name: team_members
            widget: list
            fields: 
              - {label: "First Name", name: "first_name", widget: "string"}
              - {label: "Last Name", name: "last_name", widget: "string"}
              - {label: "Position Title", name: "position_title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Headshot", name: "headshot", widget: "image", media_folder:'team'}
              - {label: "LinkedIn Profile", name: "profile_url", widget: "string"}

            
